name: linux

# concurrency:
#   group: linux-${{ github.head_ref || github.ref }}
#   cancel-in-progress: true

on:
  push:
    branches:
      - fix-mpi-fortran-flacky-test
      # Stable branches such as 0.56 or the eventual 1.0
      - '[0-9]+.[0-9]+'
    paths:
      - "mesonbuild/**"
      - "test cases/**"
      - "unittests/**"
      - ".github/workflows/images.yml"
      - ".github/workflows/os_comp.yml"
      - "run_unittests.py"
  pull_request:
    paths:
      - "mesonbuild/**"
      - "test cases/**"
      - "unittests/**"
      - ".github/workflows/images.yml"
      - ".github/workflows/os_comp.yml"
      - "run_unittests.py"

permissions:
  contents: read

jobs:
  arch:
    name: ${{ matrix.cfg.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { name: Arch Linux,       id: arch     }
          # - { name: CUDA (on Arch),   id: cuda     }
          # - { name: Fedora,           id: fedora   }
          # - { name: OpenSUSE,         id: opensuse }
          # - { name: Ubuntu Bionic,    id: bionic   }
    container: mesonbuild/${{ matrix.cfg.id }}:latest
    env:
      MESON_CI_JOBNAME: linux-${{ matrix.cfg.id }}-gcc

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      # All environment variables are stored inside the docker image in /ci/env_vars.sh
      # They are defined in the `env` section in each image.json. CI_ARGS should be set
      # via the `args` array ub the image.json
      run: |
        bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./run_tests.py --no-unittests --only "frameworks/17 mpi" $CI_ARGS'
        bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./run_tests.py --no-unittests --only "frameworks/17 mpi" $CI_ARGS'
        bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./run_tests.py --no-unittests --only "frameworks/17 mpi" $CI_ARGS'
        bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./run_tests.py --no-unittests --only "frameworks/17 mpi" $CI_ARGS'
        bash -c 'source /ci/env_vars.sh; cd $GITHUB_WORKSPACE; ./run_tests.py --no-unittests --only "frameworks/17 mpi" $CI_ARGS'

  pypy:
    name: 'Arch / PyPy'
    runs-on: ubuntu-latest
    container: mesonbuild/arch:latest
    env:
      MESON_CI_JOBNAME_UPDATE: linux-arch-gcc-pypy

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        source /ci/env_vars.sh
        export MESON_CI_JOBNAME=$MESON_CI_JOBNAME_UPDATE
        pypy3 run_tests.py --no-unittests --only "frameworks/17 mpi"
        pypy3 run_tests.py --no-unittests --only "frameworks/17 mpi"
        pypy3 run_tests.py --no-unittests --only "frameworks/17 mpi"
        pypy3 run_tests.py --no-unittests --only "frameworks/17 mpi"
        pypy3 run_tests.py --no-unittests --only "frameworks/17 mpi"

